name: go-checker
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Install GolangCI-Lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s $version
      env:
        version: v1.27.0

    - name: Lint
      run: ./bin/golangci-lint run
          
    - name: Test
      run: |
        make test
